default_stages: ['pre-commit']
default_install_hook_types: [pre-commit, commit-msg, pre-push]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: requirements-txt-fixer

  - repo: https://github.com/bwhmather/ssort
    rev: 0.15.0
    hooks:
      - id: ssort

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.0
    hooks:
      - id: ruff
        args: ["--force-exclude"]
      - id: ruff-format
        args: ["--force-exclude"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
      - id: commitizen
