
name: CI -> Tests, Lint, Types, Security
on:
  push:
    branches: [ main ]
    tags: [ "*.*.*" ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-
      - name: Cache tox env
        uses: actions/cache@v4
        with:
            path: .tox
            key: ${{ runner.os }}-tox-${{ matrix.python-version }}-${{ hashFiles('**/pyproject.toml','**/tox.ini') }}
            restore-keys: |
              ${{ runner.os }}-tox-${{ matrix.python-version }}-
              ${{ runner.os }}-tox-
      - name: Install tox
        run: pip install tox tox-pdm
      - name: Run tests
        run: tox -e tests

  typing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.13-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.13-
            ${{ runner.os }}-pip-
      - name: Cache tox env
        uses: actions/cache@v4
        with:
          path: .tox
          key: ${{ runner.os }}-tox-3.13-${{ hashFiles('**/pyproject.toml','**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-3.13-
            ${{ runner.os }}-tox-
      - run: pip install tox tox-pdm
      - run: tox -e typing

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.13-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.13-
            ${{ runner.os }}-pip-
      - name: Cache tox env
        uses: actions/cache@v4
        with:
          path: .tox
          key: ${{ runner.os }}-tox-3.13-${{ hashFiles('**/pyproject.toml','**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-3.13-
            ${{ runner.os }}-tox-
      - run: pip install tox tox-pdm
      - run: tox -e precommit

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.13-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.13-
            ${{ runner.os }}-pip-
      - name: Cache tox env
        uses: actions/cache@v4
        with:
          path: .tox
          key: ${{ runner.os }}-tox-3.13-${{ hashFiles('**/pyproject.toml','**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-3.13-
            ${{ runner.os }}-tox-
      - run: pip install tox tox-pdm
      - run: tox -e docs

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.13-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.13-
            ${{ runner.os }}-pip-
      - name: Cache tox env
        uses: actions/cache@v4
        with:
          path: .tox
          key: ${{ runner.os }}-tox-3.13-${{ hashFiles('**/pyproject.toml','**/tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-tox-3.13-
            ${{ runner.os }}-tox-
      - run: pip install tox tox-pdm
      - run: tox -e security

  build:
    runs-on: ubuntu-latest
    needs: [tests, typing, lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-3.13-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-3.13-
            ${{ runner.os }}-pip-
      - run: pip install build
      - name: Build sdist & wheel
        run: python -m build
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

