
name: CD -> Bump version and create release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  bump-version:
    if: endsWith(github.event.head_commit.message, '[tag]') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: "Bump version, create changelog and release"
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: pip
          cache-dependency-path: pyproject.toml
      - name: Setup uv
        uses: astral-sh/setup-uv@v1
      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-3.13-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-3.13-
            ${{ runner.os }}-uv-
      - name: Install build tooling
        run: pip install commitizen tox tox-uv twine
      - name: Version bump & changelog
        uses: commitizen-tools/commitizen-action@0.21.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          changelog_increment_filename: body.md
      - name: Build sdist & wheel (tox)
        run: tox -e build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: body.md
          tag_name: ${{ env.REVISION }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
